# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "docker" do |d|
    d.pull_images "difegue/lanraragi"
    d.run "difegue/lanraragi",
      args: "-p 3000:3000 --mount type=bind,source=/vagrant,target=/home/koyomi/lanraragi/content"
  end

end
