name: 'Docker builder'
inputs:
  platform:
    required: true
  docker-username:
    required: true
  docker-password:
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare
      shell: bash
      run: |
        platform=${{ inputs.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_SUMMARY: false
      with:
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY_IMAGE }}
        cache-from: type=gha,scope=buildkit-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,mode=max,scope=buildkit-${{ env.PLATFORM_PAIR }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
        file: ./tools/build/docker/Dockerfile
    - name: Export digest
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
