#!/usr/bin/env perl

use strict;
use warnings;

use local::lib;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib"; }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('LANraragi');
